[package]
name = "dbf2csv"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dbase = "0.4.0"
csv = "1.3.0"
indicatif = "0.17.7"

[build-dependencies]
winres = "0.1.12"
